server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: http://localhost:${server.port}/eureka
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.85
