server:
  port: 8050
spring:
  application:
    name: cartservice
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
product:
  jms:
    destination: product
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka    